project:
  type: website
  output-dir: docs
  #post-render: encrypt.r

website:
  title: "Data Science for Health and Biomedical Sciences"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - Week 1
      - Week 2

format:
  html:
    theme: spacelab
    css: styles.css
    toc: true



