project:
  type: book
  output-dir: docs
  #post-render: encrypt.r

book:
  title: "Data Science book"
  author: "Norah Jones"
  date: "22/04/2025"
  chapters:
    - index.qmd
    - intro.qmd
    - your-first-markdown-doc.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: spacelab
  pdf:
    documentclass: scrreprt



